import type { Metadata } from 'next';
import { Poppins, Orbitron } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import Navbar from '@/components/Navbar/Navbar';
import Logo from '@/public/logo.png';

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
});
const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${orbitron.variable}`}>
        <Navbar
          logoSrc='/logo.png'
          logoAlt='Site Logo'
          logoHref='/'
          links={[
            { href: '/characters', text: 'Characters' },
            { href: '/films', text: 'Films' },
          ]}
        />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
