import type { Metadata } from 'next';
import { Poppins, Orbitron } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
});
const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${orbitron.variable}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
